In [138]:
import requests
import pandas as pd

## Obtención de datos

In [139]:
# Extraer varias páginas
all_shows = []
for page in range(5):
    url = f"https://api.tvmaze.com/shows?page={page}"
    resp = requests.get(url)
    all_shows.extend(resp.json())

# Convertir a DataFrame y explorar
df = pd.DataFrame(all_shows)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1208 entries, 0 to 1207
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              1208 non-null   int64
 1   url             1208 non-null   object
 2   name            1208 non-null   object
 3   type            1208 non-null   object
 4   language        1208 non-null   object
 5   genres          1208 non-null   object
 6   status          1208 non-null   object
 7   runtime         1141 non-null   float64
 8   averageRuntime  1207 non-null   float64
 9   premiered       1207 non-null   object
 10  ended           1081 non-null   object
 11  officialSite    646 non-null    object
 12  schedule        1208 non-null   object
 13  rating          1208 non-null   object
 14  weight          1208 non-null   int64
 15  network         1148 non-null   object
 16  webChannel      70 non-null     object
 17  dvdCountry      2 non-null      object
 18  externals       1208 non-null   object
 19  image           1207 non-null   object
 20  summary         1208 non-null   object
 21  updated         1208 non-null   int64
 22  _links          1208 non-null   object
dtypes: float64(2), int64(3), object(18)
memory usage: 217.2+ KB

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60.0,2013-06-24,...,{'average': 6.5},100,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1758078621,{'self': {'href': 'https://api.tvmaze.com/show...
1,2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60.0,2011-09-22,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1756334491,{'self': {'href': 'https://api.tvmaze.com/show...
2,3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60.0,2014-01-11,...,{'average': 7.4},95,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
3,4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60.0,2012-10-10,...,{'average': 7.4},99,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1736039613,{'self': {'href': 'https://api.tvmaze.com/show...
4,5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63.0,2014-01-12,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1725758278,{'self': {'href': 'https://api.tvmaze.com/show...

## Transform

### Qué columnas voy a usar

In [140]:
# Elegir columnas utiles
df_clean = df[[
    'id', 'name', 'genres', 'status', 'language', 'premiered', 'network'
]]
# Extraer rating promedio
df_clean['rating'] = df['rating'].apply(lambda x: x['average'] if x else None)
df_clean

C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\4282945174.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['rating'] = df['rating'].apply(lambda x: x['average'] if x else None)

,id,name,genres,status,language,premiered,network,rating
0,1,Under the Dome,"[Drama, Science-Fiction, Thriller]",Ended,English,2013-06-24,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",6.5
1,2,Person of Interest,"[Action, Crime, Science-Fiction]",Ended,English,2011-09-22,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",8.8
2,3,Bitten,"[Drama, Horror, Romance]",Ended,English,2014-01-11,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",7.4
3,4,Arrow,"[Drama, Action, Science-Fiction]",Ended,English,2012-10-10,"{'id': 5, 'name': 'The CW', 'country': {'name'...",7.4
4,5,True Detective,"[Drama, Crime, Thriller]",Running,English,2014-01-12,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",8.1
...,...,...,...,...,...,...,...,...
1203,1245,Ironside,"[Drama, Action, Crime]",Ended,English,2013-10-02,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",7.7
1204,1246,The Jeff Dunham Show,[Comedy],Ended,English,2009-10-22,"{'id': 23, 'name': 'Comedy Central', 'country'...",6.6
1205,1247,Gooische Vrouwen,"[Drama, Romance]",Ended,Dutch,2005-10-30,"{'id': 112, 'name': 'RTL4', 'country': {'name'...",NaN
1206,1248,Blossom,"[Drama, Comedy, Family]",Ended,English,1990-07-05,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",7.4
1207,1249,The Brady Bunch,"[Comedy, Family]",Ended,English,1969-09-26,"{'id': 3, 'name': 'ABC', 'country': {'name': '...",7.1

### Manejo de nulos

In [141]:
# Miro los nulos y luego veo en cada columna los que hay
df_clean.isnull().sum()

id             0
name           0
genres         0
status         0
language       0
premiered      1
network       60
rating       155
dtype: int64

In [142]:
# Premiered hay un nulo, no molesta por lo que lo dejo como nulo.
# Ratings tiene muchos nulos, puedo sacar la media o dejarlos como nulos, no molestan.
# Network tiene nulos, unknown
df_clean["network"] = df_clean["network"].fillna("Unknown")

df_clean.isnull().sum()

C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\4047131917.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["network"] = df_clean["network"].fillna("Unknown")

id             0
name           0
genres         0
status         0
language       0
premiered      1
network        0
rating       155
dtype: int64

### Manejo de duplicados

In [143]:
# Chequeo que no haya duplicados en los id
df_clean.duplicated(subset=['id']).sum()
df_clean

,id,name,genres,status,language,premiered,network,rating
0,1,Under the Dome,"[Drama, Science-Fiction, Thriller]",Ended,English,2013-06-24,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",6.5
1,2,Person of Interest,"[Action, Crime, Science-Fiction]",Ended,English,2011-09-22,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",8.8
2,3,Bitten,"[Drama, Horror, Romance]",Ended,English,2014-01-11,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",7.4
3,4,Arrow,"[Drama, Action, Science-Fiction]",Ended,English,2012-10-10,"{'id': 5, 'name': 'The CW', 'country': {'name'...",7.4
4,5,True Detective,"[Drama, Crime, Thriller]",Running,English,2014-01-12,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",8.1
...,...,...,...,...,...,...,...,...
1203,1245,Ironside,"[Drama, Action, Crime]",Ended,English,2013-10-02,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",7.7
1204,1246,The Jeff Dunham Show,[Comedy],Ended,English,2009-10-22,"{'id': 23, 'name': 'Comedy Central', 'country'...",6.6
1205,1247,Gooische Vrouwen,"[Drama, Romance]",Ended,Dutch,2005-10-30,"{'id': 112, 'name': 'RTL4', 'country': {'name'...",NaN
1206,1248,Blossom,"[Drama, Comedy, Family]",Ended,English,1990-07-05,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",7.4
1207,1249,The Brady Bunch,"[Comedy, Family]",Ended,English,1969-09-26,"{'id': 3, 'name': 'ABC', 'country': {'name': '...",7.1

### Normalización

In [144]:
# Ver los tipos de datos de las columnas
df_clean.dtypes
# premeried debería ser datetime
df_clean['premiered'] = pd.to_datetime(df_clean['premiered'], errors='coerce')
# rating debería ser float
df_clean['rating'] = pd.to_numeric(df_clean['rating'], errors='coerce')
df_clean.dtypes

C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\687682937.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['premiered'] = pd.to_datetime(df_clean['premiered'], errors='coerce')
C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\687682937.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['rating'] = pd.to_numeric(df_clean['rating'], errors='coerce')

id                    int64
name                 object
genres               object
status               object
language             object
premiered    datetime64[ns]
network              object
rating              float64
dtype: object

In [145]:
# Paso a Mayusculas
df_clean['status'] = df_clean['status'].str.capitalize()
df_clean['language'] = df_clean['language'].str.capitalize()

C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\1840465208.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['status'] = df_clean['status'].str.capitalize()
C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\1840465208.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['language'] = df_clean['language'].str.capitalize()

### Acomodar la columna Network

In [146]:
# Extraer 'name' de network, manejar nulos
df_clean['network'] = df_clean['network'].apply(lambda x: x['name'] if isinstance(x, dict) and x.get('name') else "Unknown")
df_clean

C:\Users\joaco\AppData\Local\Temp\ipykernel_5340\1929595896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['network'] = df_clean['network'].apply(lambda x: x['name'] if isinstance(x, dict) and x.get('name') else "Unknown")

,id,name,genres,status,language,premiered,network,rating
0,1,Under the Dome,"[Drama, Science-Fiction, Thriller]",Ended,English,2013-06-24,CBS,6.5
1,2,Person of Interest,"[Action, Crime, Science-Fiction]",Ended,English,2011-09-22,CBS,8.8
2,3,Bitten,"[Drama, Horror, Romance]",Ended,English,2014-01-11,CTV Sci-Fi Channel,7.4
3,4,Arrow,"[Drama, Action, Science-Fiction]",Ended,English,2012-10-10,The CW,7.4
4,5,True Detective,"[Drama, Crime, Thriller]",Running,English,2014-01-12,HBO,8.1
...,...,...,...,...,...,...,...,...
1203,1245,Ironside,"[Drama, Action, Crime]",Ended,English,2013-10-02,NBC,7.7
1204,1246,The Jeff Dunham Show,[Comedy],Ended,English,2009-10-22,Comedy Central,6.6
1205,1247,Gooische Vrouwen,"[Drama, Romance]",Ended,Dutch,2005-10-30,RTL4,NaN
1206,1248,Blossom,"[Drama, Comedy, Family]",Ended,English,1990-07-05,NBC,7.4
1207,1249,The Brady Bunch,"[Comedy, Family]",Ended,English,1969-09-26,ABC,7.1

## Enriquecimiento

In [147]:
# Separo los generos en distintas filas
df_exploded = df_clean.explode('genres')
df_exploded

,id,name,genres,status,language,premiered,network,rating
0,1,Under the Dome,Drama,Ended,English,2013-06-24,CBS,6.5
0,1,Under the Dome,Science-Fiction,Ended,English,2013-06-24,CBS,6.5
0,1,Under the Dome,Thriller,Ended,English,2013-06-24,CBS,6.5
1,2,Person of Interest,Action,Ended,English,2011-09-22,CBS,8.8
1,2,Person of Interest,Crime,Ended,English,2011-09-22,CBS,8.8
...,...,...,...,...,...,...,...,...
1206,1248,Blossom,Drama,Ended,English,1990-07-05,NBC,7.4
1206,1248,Blossom,Comedy,Ended,English,1990-07-05,NBC,7.4
1206,1248,Blossom,Family,Ended,English,1990-07-05,NBC,7.4
1207,1249,The Brady Bunch,Comedy,Ended,English,1969-09-26,ABC,7.1
1207,1249,The Brady Bunch,Family,Ended,English,1969-09-26,ABC,7.1

## Load

In [ ]:
import os

os.makedirs("../data/raw", exist_ok=True)
os.makedirs("..//data/processed", exist_ok=True)

#Guardo raw
df.to_csv("../data/raw/shows_raw.csv", index=False)

# Guardar preprocesado
df_clean.to_csv("../data/processed/shows_clean.csv", index=False)